### ISSUE TITLE
runLatest buildLatest

### ISSUE THREAD

**Issue by coderofsalvation** [polonskiy/crowdr#22]
This is just a brainstorm based on a feature i noticed on kubernetes.
I'm really interested in other people's opinions.
Basically it solves this problem using crowdr:
- when i run `crowdr run` it tries to run _all_ services
- when i run `crowdr build` it tries to build _all_ services

Eventhough this is handy during development , it can be quite bruteforce restarting only one container in a production environment. (I find myself fiddling with docker commands as a workaround)

Proposal, allow intelligent builds / run:
1. `crowdr run` will skip trying to run containers which are already running
2. `crowdr build` will only rebuild those containers which Dockerfile (or git HEAD) has changed. 
3. `crowdr run <name>` will try to run only a certain container from the configfile
4. `crowdr build <name>` will try to build only a certain container

Not really sure if these should be native crowdr features, or just a hook.
It raises the question: what is the scope of crowdr..how much should it do?
### Inspiration:

I noticed that in a kubernetes clusterconfig (similar to `crowdr.cfg.sh`) they are specifying the 'Dockerfile'. So I was wondering, why would you want to specify that?
Well it turns out you can specify tags like 'Dockerfile:pullLatest' etc.
This means that it won't rebuild _all_ the images unless the dockerfile was updated in the registry.
I'm not really using the registry, but I could see the benefit of not having to rebuild a container when its git HEAD, or Dockerfile hasn't been changed.

**Comment by polonskiy** [comment]
Crowdr was designed as a solution for common container tasks (build/start/stop/remove/etc).
One crowdr config - multiple containers, but one logical service.
Because of that, all containers treated as a whole and all commands (except `exec` and `shell`) applied to all containers.
Build/restart/etc for a certain container does not fit in the current crowdr paradigm.

Also, proper design of your services mitigate needs for such tasks. If your containers loosely coupled and ephemeral, restart of all containers should not be a problem here. And Docker build cache mitigate a problem with separate builds.

For more fine grained control we always have the Docker :smile:

**Comment by coderofsalvation** [comment]
agreed, crowdr shouldn't worry about this.
Docker cmds are indeed perfect for this, however i really like crowdr for abstracting away all the docker plumbing.
So I was thinking a bit, and than I realized that actually what i need is like `git aliases` for crowdr.

This is what I came up with: https://github.com/polonskiy/crowdr/pull/24

The PR allows adding commands to crowdr (executable files in the hooksdir).
This prevents the user from doing manual plumbing, or having shellscripts floating around his project.
The extra cmds also inherit all crowdr env-vars + functions which is pretty neato.

WDYT?

**Comment by polonskiy** [comment]
Should we mix this functionality with hooks?
What about separate directory, like `.crowdr/cmd`?

**Comment by coderofsalvation** [comment]
maybe that's a better place.
If you want i can replace the pull request with that.

**Comment by polonskiy** [comment]
Yes, please.
